### ISSUE TITLE
change video quality

### ISSUE THREAD

**Issue by LeonimusTTV** [Athlon1600/youtube-downloader#106]
I looked at the preview of the video and noticed that it was not very good quality, so I would like to know how to change the quality in the video

**Comment by AgentSmith0** [comment]
This is possible, you can search for a different itag with higher quality in the links response. But these videos are separated into video and audio, so will need a program like ffmpeg to merge them together.

**Comment by Athlon1600** [comment]
> I looked at the preview of the video and noticed that it was not very good quality, so I would like to know how to change the quality in the video

that demo app that's hosted on heroku simply fetches the first available "combined" stream and shows that. Those combined streams where video and audio have already been merged into one by YouTube typically tend to be of lower quality.

@AgentSmith0 is right in that you could just select individual video-only and audio-only streams of the highest available quality, and then merge them manually quite easily with ffmpeg (official youtube-dl does it just like that behind the scenes).

A functionality like that will be incorporated into youtube-downloader eventually since it's already on my to-do list:
https://github.com/Athlon1600/youtube-downloader#to-do-list
