### ISSUE TITLE
1080p and 480p video quality

### ISSUE THREAD

**Issue by fcolaci** [Athlon1600/youtube-downloader#11]
Hello,

First, thanks for the script. It's very good!

I have a question ... How do I get the 1080p and 480p links?
When I try to extract them only appears 720p and 360p.

Thank you.

Ps: A suggestion ... The script could have an option to download directly, not playing the video in the browser.

**Comment by mattjis** [comment]
> How do I get the 1080p and 480p links?

Those quality options aren't available because they are split files (separated video and audio) and are sometimes unavailable needing an additional download of a manifest before you can find them.

> The script could have an option to download directly, not playing the video in the browser

Here's a single line you could use to save the 720p video instead of streaming it:
`file_put_contents("youtube.mp4", fopen($links[22]['url'], "r"));`

You can do whatever you please with the returned urls!

**Comment by fcolaci** [comment]
Thanks for the explanations @mattjis.
