### ISSUE TITLE
Install without composer

### ISSUE THREAD

**Issue by AgentSmith0** [Athlon1600/youtube-downloader#112]
Is there a way to load the library and dependencies without composer? Or is it possible to create a release that contains a loader file? Previously I used php-download.com, but now you must pay for using the service.
Thanks!

**Comment by Athlon1600** [comment]
I assume you are trying to use this library on a shared server or some place where you don't have access to the command line? 
Wasn't aware of php-download.com, so I signed up and they gave me this zip file back:
[athlon1600_youtube_downloader_9999999_dev_require.zip](https://github.com/Athlon1600/youtube-downloader/files/6593564/athlon1600_youtube_downloader_9999999_dev_require.zip)

don't know how useful this would be since including libraries this way makes it more difficult to receive future updates, but if that's good enough for some people, then it wouldn't be too difficult for me to include these "self-contained" zip files with each release.

**Comment by AgentSmith0** [comment]
Thank you, the zip file is what I needed. If it is not making to much work, it would be nice to get such a zip for the upcoming releases.

**Comment by superbmario** [comment]
Just wanted to add my +1 for this. Adding such a zip to releases would be super useful.
