### ISSUE TITLE
some videos can't be downloaded

### ISSUE THREAD

**Issue by chadul** [Athlon1600/youtube-downloader#12]
some videos like vevo videos can't be downloaded it return 403.

demo: https://api.unblockvideos.com/youtube_downloader?id=https://www.youtube.com/watch?v=fyaI4-5849w

**Comment by Athlon1600** [comment]
Try now

**Comment by chadul** [comment]
@Athlon1600 still happened brother

**Comment by Athlon1600** [comment]
Which video then?

**Comment by chadul** [comment]
@Athlon1600 https://api.unblockvideos.com/youtube_downloader?id=https://www.youtube.com/watch?v=fyaI4-5849w

**Comment by chadul** [comment]
@Athlon1600 please fix

**Comment by Athlon1600** [comment]
All those 4 links from that API response work just fine work me? Are you using the latest version? What HTTP response are you getting when you try viewing those videos?

**Comment by chadul** [comment]
@Athlon1600 403 I just tried from your demo url

**Comment by cristalix** [comment]
Same problem for me for this video: https://www.youtube.com/watch?v=MfUGPsssytQ

I cannot download the files due to 403 header and see only white screen. I have downloaded and tested tha latest version of the script locally. Youtube-dl works:

`youtube-dl -g -f 22 https://www.youtube.com/watch?v=MfUGPsssytQ`

My tip is there will be problem with signature decipher.

**Debug note:**

When I test it https://api.unblockvideos.com/youtube_downloader?id=MfUGPsssytQ&selector=mp4&redirect=false  on your "live test", @Athlon1600, I receive an extra message "invalid parameters" because the video is also georestricted in North America  https://polsy.org.uk/stuff/ytrestrict.cgi?ytid=MfUGPsssytQ

**Comment by nwer07** [comment]
i get the same error with vevo videos  HTTP ERROR 403 :/

**Comment by mesbahulalam** [comment]
Sorry to post here about a non-issue thing, but I am new to github and I tried for 20 minutes to create a pull request but couldn't figure out how to. Athlon1600, I might be able to help you with the age restricted videos. But I can't do anything to do it officially, since I registered just today, I can't find my way around in here.

**Comment by Athlon1600** [comment]
Try replacing this part in your video links:  
https://**r3---sn-vgqs7ney**.googlevideo.com/videoplayback?  
  
with:  
https://**redirector**.googlevideo.com/videoplayback?    
  
because "getDownloadLinks" returns video links from specific google servers which you may not have permission acessing.

**Comment by chadul** [comment]
Replacing to "redirector"  doesn't solved the issue still returns 403

**Comment by rayhanz** [comment]
@nwer07  Your given link works fine for me.I prefer you recheck.

**Comment by Athlon1600** [comment]
I assume he got it working now. It seems to be working for everyone else?
