### ISSUE TITLE
Couldn't parse id

### ISSUE THREAD

**Issue by MeShootIn** [Athlon1600/youtube-downloader#129]
Method `Utils::extractVideoId` doesn't parse correctly some links (tested on [https://gist.github.com/rodrigoborgesdeoliveira/987683cfbfcc8d800192da1e73adc486](url)):

- http://www.youtube.com/attribution_link?a=JdfC0C9V6ZI&u=/watch?v=EhxJLojIE_o&feature=share
- https://www.youtube.com/attribution_link?a=8g8kPrPIi-ecwIsS&u=/watch?v=yZv2daTWRZU&feature=em-uploademail
- https://www.youtube.com/user/IngridMichaelsonVEVO#p/a/u/1/QdK8U-VIH_o
- https://www.youtube-nocookie.com/embed/up_lNV-yoK4?rel=0
- http://www.youtube.com/ytscreeningroom?v=NRHVzbJVx8I
- http://www.youtube.com/user/SilkRoadTheatre#p/a/u/2/6dwqZw0j_jY
- http://www.youtube.com/watch?feature=player_embedded&v=dQw4w9WgXcQ
- http://www.youtube.com/?feature=player_embedded&v=dQw4w9WgXcQ
- http://www.youtube.com/user/IngridMichaelsonVEVO#p/u/11/KdwsulMb8EQ
- http://www.youtube-nocookie.com/v/6L3ZvIMwZFM?version=3&hl=en_US&rel=0
- http://www.youtube.com/user/dreamtheater#p/u/1/oTJRivZTMLs
- http://www.youtube.com/ytscreeningroom?v=oTJRivZTMLs

So, maybe use another method like below?
> public static function extractVideoId($str)
> {
> if (preg_match('/(?:\/|%3D|v=|vi=)([0-9A-z-_]{11})(?:[%#?&]|$)/ui', $str, $matches)) {
> return $matches[1];
> }
>
> return false;
> }

**Comment by AgentSmith0** [comment]
I would recommend creating a seperate function for this. The getDownloadLinks() function would then only accept the returned youtube id. This would slightly increase the performance when only the id is given.

**Comment by Athlon1600** [comment]
yeah, the existing ID parsing logic is pretty weak... your regex solution is much better. So we'll just use that in the next release:
https://github.com/Athlon1600/youtube-downloader/blob/250f575cd82d39f8248dd07b0cf126fe3a1bd459/src/Utils/Utils.php#L12-L23

> I would recommend creating a seperate function for this. The getDownloadLinks() function should then only accept the returned youtube id. This would slightly increase the performance when only the id is given.

true. But a good solution to that is to first check if the string passed in is exactly 11 characters long (very efficient operation), and if so, assume that the ID itself was passed in rather than some URL
