### ISSUE TITLE
How can I get a direct link to an mp4 file?

### ISSUE THREAD

**Issue by Benji-Collins** [Athlon1600/youtube-downloader#33]
Currently getDownloadLinks gives a link which when opened, plays the video. Is there a way to just get a link to the .mp4 file for downloading?

**Comment by darken26** [comment]
this happen because your browser open the video file instead of download it
there is a way in browser side, you must right click on the link and choose the save as ... , or you can add a html5 attribute to your links like following line :

`<a href="path/to/file" **download**>Click here to download</a>`

and always when you click on the link, you force the browser to download the file.
i hope this was helpful for you

**Comment by halesyy** [comment]
Hey @darken26 - I have been on this issue for about an hour trying to figure out a way to fix this. I've got **download** attribute on my element, though it still won't open and download the file. If you try to recreate the issue on your side, I can assure you that it will do the same? Jack.

**Comment by halesyy** [comment]
I'm still actively looking for a response to this.

**Comment by Athlon1600** [comment]
I think the issue here is that none of the web-browsers will allow you to force the download of a file if that file is hosted on a different server.

So unless you are hosting your site on .googlevideo.com, you are out of luck.

> Firefox only allows users to download files of the same origin due to a security concern. The file must come from your own server or domain name, otherwise it will be opened in the browser.
