### ISSUE TITLE
only 360p video available with audio other video have no audio

### ISSUE THREAD

**Issue by azinkey** [Athlon1600/youtube-downloader#44]
its only get a single video file mp4 360p in video/audio format rest are only video no audio

**Comment by sam9177** [comment]
If music video it's ok

**Comment by codezi** [comment]
Same problem.

**Comment by Athlon1600** [comment]
This is beyond my control. Most of the links that YouTube returns, are either video-only or audio-only. But as long as there is at least one video+audio, you should be good. Otherwise you'd have to download video and audio separately, and then somehow find a way to merge those two together just like youtube-dl does.
