### ISSUE TITLE
Server IP blocked by Youtube, We have been receiving a large volume of requests from your network

### ISSUE THREAD

**Issue by azinkey** [Athlon1600/youtube-downloader#52]
First Thank you for your awesome contribution, have made a test site youtube37 . com which is performing very well now. But now as I have continuously gaining users so every week my IP blocked. do you have any solution for that ? also can you recommended a cheap hosting with ffmpeg support and support to add custom IP as well. currently using dreamhost's shared hosting.

Thanks once again.

**Comment by Athlon1600** [comment]
> But now as I have continuously gaining users so every week my IP blocked. do you have any solution for that ?

not yet... I have something built for my own personal use, but it's nowhere near ready for production.

Basically I don't believe YouTube ever really blocks your IP address, it just makes you solve a captcha which is possible to automate if running through a service like 2captcha.com.

I'll have something eventually, but I'm nowhere close. Don't do too many requests from same IP.

> also can you recommended a cheap hosting with ffmpeg support and support to add custom IP as well. currently using dreamhost's shared hosting.

no idea. dreamhost is terrible, and I am not even sure if it would allow you running ffmpeg on it.
I would instead buy up a bunch of tiny VPS instances from linode or digitalocean and spread whatever you're doing over multiple servers each with its own separate IP address, so that way you don't get blocked so quickly. It gets complicated...
