### ISSUE TITLE
can't download videos

### ISSUE THREAD

**Issue by toufikwb** [Athlon1600/youtube-downloader#62]
when i put link in a ahref with download attribute it opens it in a new tab but not downloading it, it says in console cross-origin.
can anyone help me to find a solution to this?
and thanks.

**Comment by Athlon1600** [comment]
Unfortunately there is just no way around this, because Chrome and other popular browsers purposely disable such use cases for security reasons.

The code:
```html
<a href="http://videos.com/my_video.mp4" download>Download</a> 
```

only works if that code itself is hosted somewhere on `videos.com`.

So that is why putting:
```html
<a href="https://r4---sn-vgqsrnll.googlevideo.com/videoplayback..." download>Download!</a>
```

on your site will not work, unless your site's domain is `googlevideo.com`...

I'm assuming you are working on some sort of web application that allows users to download youtube videos. And so the only way to make something like that, is to have your application download that youtube video **to its own server** first, and then once you have the video file on your server, you can trigger that download in whatever way you want.
It will be eating a lot of your bandwidth, but that I think is the only way to have something like this. And I know because I'm already working on such "online youtube video downloader" web app, and that is how I am going to be doing this.
