### ISSUE TITLE
Downloading speed is very low

### ISSUE THREAD

**Issue by jahanzaibniazi** [Athlon1600/youtube-downloader#63]
I am hosting that library on the shared hosting account, but download speed is very low. What could be a reason for that? I noted that it downloads full file as a whole which may be a cause of slow speed. As files are downloaded in small streams and then combined which makes download faster. So please clarify this issue.

**Comment by mhhakim** [comment]
As far as I know, the file downloads directly from google's server. So, there's nothing to do with your hosting. 

Is your internet speed fast enough? Did you try another video? You can use any download manager which should help you to get good download speed.

**Comment by Athlon1600** [comment]
> I am hosting that library on the shared hosting account, but download speed is very low. What could be a reason for that?

I'm guessing since you are on shared hosting, you have a bunch of people sharing the same internet connection, and if any of those people on that same network, also make a lot of download requests to youtube, then youtube starts throttling speed to that IP address.  
This happens to me all the time whenever I want to download all the videos from a particular youtube channel. First video  downloads really fast, and then the speed just gets progressively slower as you download more and more videos in short period of time, so that by the time you're downloading video number 87, you're either already blocked by youtube (captcha) for making too many requests or the download speed is 1/10th of what it was with the first video.

There is just no way around this other than by spreading your connections across multiple servers or multiple IP addresses at least.

> As files are downloaded in small streams and then combined which makes download faster.

that would not make any difference whatsoever.
