### ISSUE TITLE
Extracting an .m4a link?

### ISSUE THREAD

**Issue by mattjis** [Athlon1600/youtube-downloader#7]
I'm wanting only the audio from youtube videos. Is this something you would consider adding to the class? If not, where would I start when trying to change something like this?

Great work by the way; youtube-dl takes upwards of 4 seconds for me and what you've made takes at most 0.3 seconds. Incredible! Plus youtube-dl seems to fail every couple of weeks and require an update to get it back in working order so the downtime really sucks! Mad props

**Comment by Athlon1600** [comment]
It's very possible, except that if I started adding all these "advanced features", the script would no longer be as fast as it is now. The reason youtube-dl is so slow is because it digs so deep into that particular YouTube video page and tries to find as much downloadable pieces of data as possible including things like audio links etc... But yes, eventually I do plan on adding more features. Stay tuned.
