### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by peter279k** [Athlon1600/youtube-downloader#75]
I want to say thanks for @Athlon1600 to provide a good repository so that I can complete this [web service](https://youtube.peterli.website/) for my family members.

And they can be easy to download a YouTube video via this service happily.

And the repository is available [here](https://github.com/peter279k/web-youtube-downloader).

**Comment by Athlon1600** [comment]
Always nice to hear! 😃 never expected this to get so many users so fast! 
The web service you built looks to be very useful. I was trying to build something like that myself to compete with the many "youtube downloaders" out there, but never got it to work at a mass scale, because after you try downloading from youtube too many times, [youtube will throw you a captcha](https://github.com/Athlon1600/youtube-downloader/issues/64).... sure, you can build a captcha solver that automatically solves that, but even that has limitations as youtube eventually realizes that you are a bot and just blocks your IP for some time with no way out.  
Definitely a useful service and good problem to solve, as there are just so many people who would use this.
