### ISSUE TITLE
https://www.youtube.com/watch?v=HDg4Ogw-BVI this link is showing that no video found...

### ISSUE THREAD

**Issue by hirazzz** [Athlon1600/youtube-downloader#80]

**Comment by Athlon1600** [comment]
probably because that video is blocked in America: https://unblockvideos.com/youtube-video-restriction-checker/#url=HDg4Ogw-BVI  
  
so if  you're running this from a computer with an American IP address, you're still going to get `The uploader has not made this video available in your country`, and there is nothing youtube-downloader can do to bypass that.
